version: '3.7'
services:
###########
### PORTAINER
###########
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    networks:
      - web
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Europe/Zurich'

###########
### Wordpress
###########
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    networks:
      - wordpress
      - web
    user: ${UID}:${GID}
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: "${DB_PW}"
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./html/:/var/www/html/
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: "${DB_PW}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PW}"
    volumes:
      - db:/var/lib/mysql
    networks:
      - wordpress

###########
### PHPmyAdmin
###########
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8888:80'
    networks:
      - web
      - wordpress
    environment:
      PMA_ARBITRARY: 1

###########
### Mailhog
###########
  mailhog:
    image: mailhog/mailhog
    ports:
#      - '1025:1025' # Doesn't need to be open to public
      - '8025:8025'
    networks:
      - web
  
volumes:
  wordpress:
  db:
  portainer:

networks:
  wordpress:
    name: wordpress
    external: false
    internal: true
  web:
    name: web
    external: true
